"""updated models.py

Revision ID: af54495e7772
Revises: aab55bef4222
Create Date: 2024-07-08 19:51:52.981110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af54495e7772'
down_revision = 'aab55bef4222'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qr_code', schema=None) as batch_op:
        batch_op.alter_column('RefNo',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Integer(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qr_code', schema=None) as batch_op:
        batch_op.alter_column('RefNo',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
