"""changed the ref no datatatype

Revision ID: e5f729b40ff7
Revises: af54495e7772
Create Date: 2024-07-09 17:12:50.455494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5f729b40ff7'
down_revision = 'af54495e7772'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qr_code', schema=None) as batch_op:
        batch_op.alter_column('RefNo',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qr_code', schema=None) as batch_op:
        batch_op.alter_column('RefNo',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
